"""Configuration, paths, download utilities, and geographic code handling for the urban economics pipeline"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = [
    "Country",
    "PROJECT_ROOT",
    "DATA_DIR",
    "PLOTS_DIR",
    "NOTEBOOKS_DIR",
    "DOCS_DIR",
    "RAW_DATA_DIR",
    "PROCESSED_DATA_DIR",
    "OUTPUT_DIR",
    "UK_LA_PREFIXES",
    "UK_LA_CODE_FIXES",
    "raw_path",
    "processed_path",
    "output_path",
    "ensure_dirs",
    "fetch_with_retry",
    "download_file",
    "is_uk_local_authority",
    "is_england_wales_la",
    "get_la_type",
    "fix_la_code",
]

# %% ../nbs/00_core.ipynb 3
import time
from pathlib import Path
from typing import Any, Literal

import requests

# %% ../nbs/00_core.ipynb 4
# Country type
Country = Literal["uk", "us"]

# %% ../nbs/00_core.ipynb 5
# Project root - navigate up from src/core.py location
PROJECT_ROOT = Path(__file__).parent.parent if "__file__" in globals() else Path.cwd()

# Base directories
DATA_DIR = PROJECT_ROOT / "data"
PLOTS_DIR = PROJECT_ROOT / "plots"
NOTEBOOKS_DIR = PROJECT_ROOT / "notebooks"
DOCS_DIR = PROJECT_ROOT / "docs"

# Data subdirectories
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
OUTPUT_DIR = DATA_DIR / "output"


# %% ../nbs/00_core.ipynb 7
def raw_path(
    country: Country,  # Country code ("uk" or "us")
    dataset: str,  # Dataset name (e.g., "epc", "pipr", "ashe")
) -> Path:
    """Get path to raw data directory for a country/dataset."""
    return RAW_DATA_DIR / country / dataset


def processed_path(
    country: Country,  # Country code ("uk" or "us")
    dataset: str,  # Dataset name
) -> Path:
    """Get path to processed data directory for a country/dataset."""
    return PROCESSED_DATA_DIR / country / dataset


def output_path(
    replication: str,  # Replication name (e.g., "yimby_rent_map", "cooped_up")
) -> Path:
    """Get path to output directory for a paper replication."""
    return OUTPUT_DIR / replication


# %% ../nbs/00_core.ipynb 10
def ensure_dirs() -> None:
    """Create all required directories if they don't exist."""
    dirs = [
        RAW_DATA_DIR,
        PROCESSED_DATA_DIR,
        OUTPUT_DIR,
        PLOTS_DIR,
        # UK raw data
        raw_path("uk", "epc"),
        raw_path("uk", "pipr"),
        raw_path("uk", "ashe"),
        raw_path("uk", "census"),
        raw_path("uk", "geography"),
        raw_path("uk", "construction"),
        # US raw data
        raw_path("us", "cbp"),
        raw_path("us", "acs"),
        raw_path("us", "saiz"),
        raw_path("us", "geography"),
        # Processed data
        processed_path("uk", "epc"),
        processed_path("uk", "pipr"),
        processed_path("us", "cbp"),
        # Outputs
        output_path("yimby_rent_map"),
        output_path("cooped_up"),
        output_path("hsieh_moretti"),
    ]
    for d in dirs:
        d.mkdir(parents=True, exist_ok=True)


# %% ../nbs/00_core.ipynb 12
def fetch_with_retry(
    url: str,
    params: dict[str, Any] | None = None,
    max_retries: int = 3,
    timeout: int = 120,
) -> dict[str, Any]:
    """
    Fetch JSON data from URL with retry logic for transient failures.

    Args:
        url: URL to fetch
        params: Optional query parameters
        max_retries: Maximum number of retry attempts
        timeout: Request timeout in seconds

    Returns:
        Parsed JSON response

    Raises:
        requests.exceptions.RequestException: If all retries fail
    """
    for attempt in range(max_retries):
        try:
            response = requests.get(url, params=params, timeout=timeout)
            response.raise_for_status()
            return response.json()
        except requests.exceptions.RequestException as e:
            if attempt < max_retries - 1:
                wait_time = 2**attempt  # Exponential backoff: 1, 2, 4 seconds
                print(f"  Request failed, retrying in {wait_time}s... ({e})")
                time.sleep(wait_time)
            else:
                raise
    return {}


def download_file(
    url: str,
    output_path: Path,
    chunk_size: int = 8192,
    timeout: int = 300,
) -> Path:
    """
    Download a file from URL to local path.

    Args:
        url: URL to download from
        output_path: Local path to save file
        chunk_size: Download chunk size in bytes
        timeout: Request timeout in seconds

    Returns:
        Path to downloaded file

    Raises:
        requests.exceptions.RequestException: If download fails
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    response = requests.get(url, stream=True, timeout=timeout)
    response.raise_for_status()

    with open(output_path, "wb") as f:
        for chunk in response.iter_content(chunk_size=chunk_size):
            f.write(chunk)

    return output_path


# %% ../nbs/00_core.ipynb 14
# UK Local Authority code prefixes
UK_LA_PREFIXES = {
    "E06": "Unitary Authority (England)",
    "E07": "Non-metropolitan District",
    "E08": "Metropolitan District",
    "E09": "London Borough",
    "W06": "Unitary Authority (Wales)",
    "S12": "Council Area (Scotland)",
    "N09": "Local Government District (NI)",
}


def is_uk_local_authority(code: str) -> bool:
    """
    Check if a code is a UK local authority code.

    Args:
        code: Geographic code to check

    Returns:
        True if code is a UK LA code
    """
    if not code or len(code) < 3:
        return False
    prefix = code[:3]
    return prefix in UK_LA_PREFIXES


def is_england_wales_la(code: str) -> bool:
    """
    Check if a code is an England or Wales local authority.

    Args:
        code: Geographic code to check

    Returns:
        True if code is an England/Wales LA code
    """
    if not code or len(code) < 3:
        return False
    prefix = code[:3]
    return prefix in ("E06", "E07", "E08", "E09", "W06")


def get_la_type(code: str) -> str | None:
    """
    Get the type of local authority from its code.

    Args:
        code: LA code

    Returns:
        LA type description or None if not recognised
    """
    if not code or len(code) < 3:
        return None
    return UK_LA_PREFIXES.get(code[:3])


# Known LA code corrections (ONS data sometimes has typos)
UK_LA_CODE_FIXES = {
    "E08000039": "E08000019",  # Sheffield (typo in ONS data)
    "E08000038": "E08000016",  # Barnsley (typo in ONS data)
}


def fix_la_code(code: str) -> str:
    """
    Apply known LA code corrections.

    Args:
        code: LA code to fix

    Returns:
        Corrected LA code
    """
    return UK_LA_CODE_FIXES.get(code, code)
