"""Iterative algorithm for finding the equilibrium distribution of workers across cities"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_equilibrium.ipynb.

# %% auto 0
__all__ = ["EquilibriumSolver", "calculate_gdp_change"]

# %% ../nbs/07_equilibrium.ipynb 2
import numpy as np
from scipy.special import logsumexp as scipy_logsumexp

from .parameters import CityParameters, EquilibriumResult, ModelParameters


# %% ../nbs/07_equilibrium.ipynb 5
class EquilibriumSolver:
    """Iterative solver for spatial equilibrium using the Fréchet/probabilistic model."""

    def __init__(
        self,
        params: ModelParameters,  # Model parameters (elasticities, shares)
        cities: list[CityParameters],  # List of city-specific parameters
    ):
        """Initialize the solver."""
        self.params = params
        self.cities = cities
        self.n_cities = len(cities)

        # Pre-compute log of city-specific parameters for efficiency
        self._log_base_tfp = np.array([np.log(c.base_tfp) for c in cities])
        self._log_amenity = np.array([np.log(c.amenity) for c in cities])
        self._supply_elasticity = np.array([c.supply_elasticity for c in cities])
        self._log_supply_shifter = np.array([np.log(c.supply_shifter) for c in cities])

    def log_rent_from_log_population(
        self,
        log_pop: np.ndarray,  # Log population in each city
    ) -> np.ndarray:
        """Calculate log rents from log population using housing market equilibrium."""
        return (log_pop - self._log_supply_shifter) / self._supply_elasticity

    def log_wage_from_log_population(
        self,
        log_pop: np.ndarray,  # Log population in each city
    ) -> np.ndarray:
        """Calculate log wages from log population using production function."""
        p = self.params
        return np.log(p.alpha) + self._log_base_tfp + (p.alpha + p.eta - 1) * log_pop

    def log_utility(
        self,
        log_wages: np.ndarray,  # Log wages in each city
        log_rents: np.ndarray,  # Log rents in each city
    ) -> np.ndarray:
        """Calculate log utility in each city."""
        return log_wages - self.params.beta * log_rents + self._log_amenity

    def log_output(
        self,
        log_pop: np.ndarray,  # Log population in each city
    ) -> np.ndarray:
        """Calculate log output in each city."""
        return self._log_base_tfp + (self.params.alpha + self.params.eta) * log_pop

    def _logsumexp(
        self,
        x: np.ndarray,  # Array of values
    ) -> float:
        """Compute log(sum(exp(x))) without overflow using scipy's implementation."""
        return float(scipy_logsumexp(x))

    def _log_softmax(
        self,
        x: np.ndarray,  # Array of values
    ) -> np.ndarray:
        """Compute log(softmax(x)) in a numerically stable way."""
        return x - scipy_logsumexp(x)

    def solve(
        self,
        total_population: float,  # Total population to distribute across cities
        tol: float = 1e-8,  # Convergence tolerance (max change in population shares)
        max_iter: int = 2000,  # Maximum iterations before giving up
        damping: float = 0.3,  # Damping factor for updates (0-1, lower = more stable)
        verbose: bool = False,  # If True, print iteration progress
    ) -> EquilibriumResult:
        """Solve for spatial equilibrium where worker shares follow the Fréchet distribution."""
        # Initial guess: equal distribution in log space
        log_total_pop = np.log(total_population)
        log_pop = np.full(self.n_cities, log_total_pop - np.log(self.n_cities))

        # Adaptive damping for high theta (more mobile workers need gentler updates)
        # Use very strong damping for high theta to prevent oscillation
        effective_damping = min(damping, 0.5 / (1.0 + self.params.theta / 5.0))

        converged = False
        iteration = 0
        for iteration in range(max_iter):
            # Calculate wages and rents in log space
            log_rents = self.log_rent_from_log_population(log_pop)
            log_wages = self.log_wage_from_log_population(log_pop)
            log_utilities = self.log_utility(log_wages, log_rents)

            # Workers move toward high-utility cities
            # share_i proportional to utility_i^theta
            # Use log_softmax for numerical stability
            log_shares = self._log_softmax(self.params.theta * log_utilities)

            # Check for numerical issues
            if not np.all(np.isfinite(log_shares)):
                # Fall back to equal shares if numerical issues
                log_shares = np.full(self.n_cities, -np.log(self.n_cities))

            # New population in log space
            new_log_pop = log_shares + log_total_pop

            # Damped update for stability
            new_log_pop = effective_damping * new_log_pop + (1 - effective_damping) * log_pop

            # Check convergence on population shares
            old_shares = np.exp(self._log_softmax(log_pop))
            new_shares = np.exp(self._log_softmax(new_log_pop))
            diff = np.abs(new_shares - old_shares).max()

            if verbose and iteration % 100 == 0:
                utilities = np.exp(log_utilities)
                util_spread = (utilities.max() / utilities.min() - 1) * 100
                print(f"Iteration {iteration}: share change = {diff:.2e}, utility spread = {util_spread:.2f}%")

            log_pop = new_log_pop

            if diff < tol:
                converged = True
                break

        # Final calculations (convert back from log space)
        population = np.exp(log_pop)
        # Renormalize to ensure exact total
        population = population * (total_population / population.sum())

        log_pop = np.log(population)
        log_rents = self.log_rent_from_log_population(log_pop)
        log_wages = self.log_wage_from_log_population(log_pop)
        log_utilities = self.log_utility(log_wages, log_rents)
        log_outputs = self.log_output(log_pop)

        rents = np.exp(log_rents)
        wages = np.exp(log_wages)
        utilities = np.exp(log_utilities)
        outputs = np.exp(log_outputs)

        return EquilibriumResult(
            city_names=[c.name for c in self.cities],
            population=population.tolist(),
            wages=wages.tolist(),
            rents=rents.tolist(),
            utilities=utilities.tolist(),
            outputs=outputs.tolist(),
            total_gdp=float(outputs.sum()),
            converged=converged,
            iterations=iteration + 1,
        )


# %% ../nbs/07_equilibrium.ipynb 7
def calculate_gdp_change(
    baseline: EquilibriumResult,  # Baseline equilibrium result
    counterfactual: EquilibriumResult,  # Counterfactual equilibrium result
) -> dict[str, float]:
    """Calculate GDP change between two equilibria."""
    gdp_change = counterfactual.total_gdp - baseline.total_gdp
    gdp_change_pct = (gdp_change / baseline.total_gdp) * 100

    return {
        "baseline_gdp": baseline.total_gdp,
        "counterfactual_gdp": counterfactual.total_gdp,
        "gdp_change": gdp_change,
        "gdp_change_pct": gdp_change_pct,
    }
