"""Housing supply functions, elasticity, and equilibrium rent determination"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_housing.ipynb.

# %% auto 0
__all__ = ["housing_supply", "equilibrium_rent", "rent_elasticity_with_respect_to_population"]

# %% ../nbs/05_housing.ipynb 2
import numpy as np


# %% ../nbs/05_housing.ipynb 4
def housing_supply(
    rent: float,  # Housing rent
    supply_shifter: float,  # Supply shifter parameter (S)
    elasticity: float,  # Supply elasticity (gamma)
) -> float:
    """Calculate housing supply given rent and supply parameters."""
    return supply_shifter * (rent**elasticity)


def equilibrium_rent(
    population: float,  # City population (= housing demand)
    supply_shifter: float,  # Supply shifter parameter (S)
    elasticity: float,  # Supply elasticity (gamma)
) -> float:
    """Calculate equilibrium rent where housing supply equals population."""
    return (population / supply_shifter) ** (1 / elasticity)


def rent_elasticity_with_respect_to_population(
    population: float,  # Current population
    supply_shifter: float,  # Supply shifter parameter
    elasticity: float,  # Supply elasticity (gamma)
) -> float:
    """Calculate the elasticity of rent with respect to population."""
    return 1 / elasticity
