"""High-level API, dataset abstractions, and counterfactual analysis"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_model.ipynb.

# %% auto 0
__all__ = [
    "RosenRobackDataset",
    "SyntheticDataset",
    "ThreeCityDataset",
    "DataFrameDataset",
    "CounterfactualScenario",
    "RosenRobackModel",
]

# %% ../nbs/08_model.ipynb 2
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any

import numpy as np
import pandas as pd

from .equilibrium import EquilibriumSolver, calculate_gdp_change
from .parameters import CityParameters, EquilibriumResult, ModelParameters


# %% ../nbs/08_model.ipynb 4
class RosenRobackDataset(ABC):
    """Abstract base class for datasets usable with the Rosen-Roback model."""

    @property
    @abstractmethod
    def name(self) -> str:
        """Human-readable name for this dataset."""

    @abstractmethod
    def get_cities(self) -> list[CityParameters]:
        """Extract city parameters from the dataset."""

    @abstractmethod
    def get_total_population(self) -> float:
        """Get the total population to distribute across cities."""

    def get_city_names(self) -> list[str]:
        """Get list of city names."""
        return [c.name for c in self.get_cities()]

    def __len__(self) -> int:
        """Number of cities in the dataset."""
        return len(self.get_cities())

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name='{self.name}', n_cities={len(self)})"


# %% ../nbs/08_model.ipynb 6
class SyntheticDataset(RosenRobackDataset):
    """Generate synthetic cities for testing and teaching."""

    def __init__(
        self,
        n_cities: int = 10,  # Number of cities to generate
        total_population: float = 10_000_000,  # Total population across all cities
        tfp_range: tuple[float, float] = (70, 130),  # Range for base TFP values
        amenity_range: tuple[float, float] = (0.7, 1.3),  # Range for amenity values
        elasticity_range: tuple[float, float] = (0.5, 3.0),  # Range for supply elasticity
        supply_shifter: float = 1000.0,  # Supply shifter for all cities
        seed: int | None = None,  # Random seed for reproducibility
    ):
        self._n_cities = n_cities
        self._total_population = total_population
        self._supply_shifter = supply_shifter
        self._cities = self._generate_cities(
            n_cities, tfp_range, amenity_range, elasticity_range, supply_shifter, seed
        )

    def _generate_cities(
        self,
        n: int,
        tfp_range: tuple[float, float],
        amenity_range: tuple[float, float],
        elasticity_range: tuple[float, float],
        supply_shifter: float,
        seed: int | None,
    ) -> list[CityParameters]:
        """Generate random city parameters."""
        rng = np.random.default_rng(seed)
        cities = []
        for i in range(n):
            cities.append(
                CityParameters(
                    name=f"City_{i + 1}",
                    base_tfp=rng.uniform(*tfp_range),
                    amenity=rng.uniform(*amenity_range),
                    supply_elasticity=rng.uniform(*elasticity_range),
                    supply_shifter=supply_shifter,
                )
            )
        return cities

    @property
    def name(self) -> str:
        return f"Synthetic ({self._n_cities} cities)"

    def get_cities(self) -> list[CityParameters]:
        return self._cities

    def get_total_population(self) -> float:
        return self._total_population


# %% ../nbs/08_model.ipynb 8
class ThreeCityDataset(RosenRobackDataset):
    """Simple three-city dataset for pedagogical examples."""

    def __init__(
        self,
        high_tfp: float = 120,  # TFP for high-productivity city
        medium_tfp: float = 100,  # TFP for medium-productivity city
        low_tfp: float = 80,  # TFP for low-productivity city
        high_elasticity: float = 1.5,  # Supply elasticity for high-productivity city
        medium_elasticity: float = 2.0,  # Supply elasticity for medium-productivity city
        low_elasticity: float = 3.0,  # Supply elasticity for low-productivity city
        total_population: float = 3_000_000,  # Total population to distribute
    ):
        self._total_population = total_population
        self._cities = [
            CityParameters(
                name="High Productivity",
                base_tfp=high_tfp,
                amenity=1.0,
                supply_elasticity=high_elasticity,
                supply_shifter=1000,
            ),
            CityParameters(
                name="Medium",
                base_tfp=medium_tfp,
                amenity=1.0,
                supply_elasticity=medium_elasticity,
                supply_shifter=1000,
            ),
            CityParameters(
                name="Low Productivity",
                base_tfp=low_tfp,
                amenity=1.0,
                supply_elasticity=low_elasticity,
                supply_shifter=1000,
            ),
        ]

    @property
    def name(self) -> str:
        return "Three Cities (HP/M/LP)"

    def get_cities(self) -> list[CityParameters]:
        return self._cities

    def get_total_population(self) -> float:
        return self._total_population


# %% ../nbs/08_model.ipynb 10
class DataFrameDataset(RosenRobackDataset):
    """Dataset backed by a pandas DataFrame with configurable column names."""

    def __init__(
        self,
        df: pd.DataFrame,  # DataFrame containing city data
        name: str,  # Human-readable name for the dataset
        name_col: str = "city",  # Column name for city names
        tfp_col: str | None = None,  # Column name for TFP values
        wage_col: str | None = None,  # Column name for wage values
        rent_col: str | None = None,  # Column name for rent values
        elasticity_col: str = "elasticity",  # Column name for supply elasticity
        population_col: str = "population",  # Column name for population
        default_elasticity: float = 2.0,  # Default elasticity if column not present
    ):
        self._df = df.copy()
        self._name = name
        self._name_col = name_col
        self._tfp_col = tfp_col
        self._wage_col = wage_col
        self._rent_col = rent_col
        self._elasticity_col = elasticity_col
        self._population_col = population_col
        self._default_elasticity = default_elasticity
        self._validate()

    def _validate(self) -> None:
        """Validate that required columns exist."""
        required = [self._name_col, self._population_col]
        missing = [col for col in required if col not in self._df.columns]
        if missing:
            raise ValueError(f"Missing required columns: {missing}")
        if self._tfp_col is None and (self._wage_col is None or self._rent_col is None):
            raise ValueError("Must provide either tfp_col or both wage_col and rent_col")

    @property
    def name(self) -> str:
        return self._name

    def get_cities(self) -> list[CityParameters]:
        """Extract city parameters from the DataFrame."""
        cities = []
        for _, row in self._df.iterrows():
            # Get TFP - either directly or infer from wages/rents
            if self._tfp_col and self._tfp_col in self._df.columns:
                base_tfp = float(row[self._tfp_col])
            else:
                wage = float(row[self._wage_col])
                rent = float(row[self._rent_col])
                base_tfp = wage / (rent**0.33)  # Using beta=0.33

            # Get elasticity
            elasticity = (
                float(row[self._elasticity_col])
                if self._elasticity_col in self._df.columns
                else self._default_elasticity
            )

            cities.append(
                CityParameters(
                    name=str(row[self._name_col]),
                    base_tfp=base_tfp,
                    amenity=1.0,
                    supply_elasticity=elasticity,
                    supply_shifter=1000.0,
                )
            )
        return cities

    def get_total_population(self) -> float:
        return float(self._df[self._population_col].sum())


# %% ../nbs/08_model.ipynb 12
@dataclass
class CounterfactualScenario:
    """Defines a counterfactual scenario for policy analysis."""

    name: str  # Short name for the scenario
    description: str  # Longer description of what changes
    elasticity_changes: dict[str, float]  # Map from city name to new elasticity

    def apply_to_dataset(
        self,
        baseline: RosenRobackDataset,  # Baseline dataset to modify
    ) -> list[CityParameters]:
        """Apply this scenario to a baseline dataset, returning modified city parameters."""
        cities = baseline.get_cities()
        new_cities = []
        for city in cities:
            if city.name in self.elasticity_changes:
                new_elasticity = self.elasticity_changes[city.name]
                new_cities.append(
                    CityParameters(
                        name=city.name,
                        base_tfp=city.base_tfp,
                        amenity=city.amenity,
                        supply_elasticity=new_elasticity,
                        supply_shifter=city.supply_shifter,
                    )
                )
            else:
                new_cities.append(city)
        return new_cities


# %% ../nbs/08_model.ipynb 14
class RosenRobackModel:
    """Multi-city Rosen-Roback spatial equilibrium model."""

    def __init__(
        self,
        params: ModelParameters | None = None,  # Model parameters (uses STANDARD if None)
    ):
        self.params = params or ModelParameters.STANDARD

    def solve(
        self,
        dataset: RosenRobackDataset,  # Dataset providing city parameters and total population
        **solver_kwargs: Any,  # Additional arguments passed to solver (tol, max_iter, damping, verbose)
    ) -> EquilibriumResult:
        """Solve for spatial equilibrium."""
        cities = dataset.get_cities()
        total_population = dataset.get_total_population()
        solver = EquilibriumSolver(self.params, cities)
        return solver.solve(total_population, **solver_kwargs)

    def solve_with_cities(
        self,
        cities: list[CityParameters],  # Explicit city parameters
        total_population: float,  # Total population to distribute
        **solver_kwargs: Any,  # Additional arguments passed to solver
    ) -> EquilibriumResult:
        """Solve equilibrium given explicit city parameters."""
        solver = EquilibriumSolver(self.params, cities)
        return solver.solve(total_population, **solver_kwargs)

    def run_counterfactual(
        self,
        dataset: RosenRobackDataset,  # Baseline dataset
        scenario: CounterfactualScenario,  # Counterfactual scenario to apply
        **solver_kwargs: Any,  # Additional arguments passed to solver
    ) -> tuple[EquilibriumResult, EquilibriumResult, dict[str, float]]:
        """Run a counterfactual analysis comparing baseline to scenario."""
        baseline = self.solve(dataset, **solver_kwargs)
        counterfactual_cities = scenario.apply_to_dataset(dataset)
        counterfactual = self.solve_with_cities(counterfactual_cities, dataset.get_total_population(), **solver_kwargs)
        gdp_comparison = calculate_gdp_change(baseline, counterfactual)
        return baseline, counterfactual, gdp_comparison
