"""Parameter dataclasses for the Rosen-Roback spatial equilibrium model"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_parameters.ipynb.

# %% auto 0
__all__ = ["ModelParameters", "CityParameters", "EquilibriumResult"]

# %% ../nbs/01_parameters.ipynb 2
from dataclasses import dataclass, field
from typing import ClassVar


# %% ../nbs/01_parameters.ipynb 4
@dataclass(frozen=True)
class ModelParameters:
    """Global parameters for the Rosen-Roback spatial equilibrium model."""

    alpha: float = 0.65  # Labour share in production (typically 0.6-0.7)
    eta: float = 0.04  # Agglomeration elasticity (standard: 0.02-0.08, Cooped Up: 0.25)
    beta: float = 0.33  # Housing expenditure share (fraction of income spent on housing)
    theta: float = 10.0  # Labour mobility (Fréchet shape). Higher = more mobile workers

    # Named parameter sets
    STANDARD: ClassVar["ModelParameters"]
    HSIEH_MORETTI: ClassVar["ModelParameters"]
    COOPED_UP: ClassVar["ModelParameters"]
    HIGH_MOBILITY: ClassVar["ModelParameters"]

    def __post_init__(self) -> None:
        """Validate parameters are in reasonable ranges."""
        if not 0 < self.alpha < 1:
            raise ValueError(f"alpha must be in (0, 1), got {self.alpha}")
        if self.eta < 0:
            raise ValueError(f"eta must be non-negative, got {self.eta}")
        if not 0 < self.beta < 1:
            raise ValueError(f"beta must be in (0, 1), got {self.beta}")
        if self.theta <= 0:
            raise ValueError(f"theta must be positive, got {self.theta}")

    def with_updates(self, **kwargs) -> "ModelParameters":
        """Create a new ModelParameters with some values updated."""
        return ModelParameters(
            alpha=kwargs.get("alpha", self.alpha),
            eta=kwargs.get("eta", self.eta),
            beta=kwargs.get("beta", self.beta),
            theta=kwargs.get("theta", self.theta),
        )


# %% ../nbs/01_parameters.ipynb 6
# Standard academic estimates with moderate mobility
ModelParameters.STANDARD = ModelParameters(
    alpha=0.65,
    eta=0.04,
    beta=0.33,
    theta=10.0,  # ~6% utility spread
)

# Hsieh-Moretti (2019) calibration
ModelParameters.HSIEH_MORETTI = ModelParameters(
    alpha=0.65,
    eta=0.25,
    beta=0.33,
    theta=2.0,  # Original paper value
)

# Cooped Up paper calibration
ModelParameters.COOPED_UP = ModelParameters(
    alpha=0.65,
    eta=0.25,
    beta=0.32,
    theta=3.33,  # Original paper value
)

# High mobility (classic Rosen-Roback with nearly equal utilities)
ModelParameters.HIGH_MOBILITY = ModelParameters(
    alpha=0.65,
    eta=0.04,
    beta=0.33,
    theta=50.0,  # ~1.5% utility spread
)


# %% ../nbs/01_parameters.ipynb 8
@dataclass
class CityParameters:
    """Parameters for a single city in the model."""

    name: str  # City identifier (e.g., "London", "Manchester")
    base_tfp: float  # Base total factor productivity (before agglomeration)
    amenity: float = 1.0  # Amenity value (how much workers like this city)
    supply_elasticity: float = 2.0  # Housing supply elasticity (gamma). SF ~0.7, Houston ~2.5
    supply_shifter: float = 1000.0  # Housing supply shifter (affects rent level)

    def __post_init__(self) -> None:
        """Validate city parameters."""
        if self.base_tfp <= 0:
            raise ValueError(f"base_tfp must be positive, got {self.base_tfp}")
        if self.amenity <= 0:
            raise ValueError(f"amenity must be positive, got {self.amenity}")
        if self.supply_elasticity <= 0:
            raise ValueError(f"supply_elasticity must be positive, got {self.supply_elasticity}")
        if self.supply_shifter <= 0:
            raise ValueError(f"supply_shifter must be positive, got {self.supply_shifter}")


# %% ../nbs/01_parameters.ipynb 10
@dataclass
class EquilibriumResult:
    """Results from solving the spatial equilibrium."""

    city_names: list[str]  # List of city names in order
    population: list[float] = field(default_factory=list)  # Equilibrium population in each city
    wages: list[float] = field(default_factory=list)  # Equilibrium wage in each city
    rents: list[float] = field(default_factory=list)  # Equilibrium rent in each city
    utilities: list[float] = field(default_factory=list)  # Worker utility in each city
    outputs: list[float] = field(default_factory=list)  # Total output produced in each city
    total_gdp: float = 0.0  # Sum of outputs across all cities
    converged: bool = False  # Whether the solver converged
    iterations: int = 0  # Number of iterations taken

    def __len__(self) -> int:
        """Number of cities."""
        return len(self.city_names)

    def to_dataframe(self):
        """Convert results to a pandas DataFrame."""
        import pandas as pd

        return pd.DataFrame(
            {
                "city": self.city_names,
                "population": self.population,
                "wage": self.wages,
                "rent": self.rents,
                "utility": self.utilities,
                "output": self.outputs,
            }
        )

    def utility_spread_pct(self) -> float:
        """Calculate percentage spread in utilities (max/min - 1)."""
        if not self.utilities:
            return 0.0
        utils = [u for u in self.utilities if u > 0]
        if not utils:
            return 0.0
        return (max(utils) / min(utils) - 1) * 100

    def summary(self) -> str:
        """Return a formatted summary string."""
        lines = [
            "Spatial Equilibrium Results",
            "=" * 70,
            f"{'City':<25} {'Population':>12} {'Wage':>10} {'Rent':>10} {'Utility':>10}",
            "-" * 70,
        ]
        for i, name in enumerate(self.city_names):
            lines.append(
                f"{name:<25} {self.population[i]:>12,.0f} "
                f"{self.wages[i]:>10.2f} {self.rents[i]:>10.2f} "
                f"{self.utilities[i]:>10.4f}"
            )
        lines.append("-" * 70)
        lines.append(f"Total GDP: {self.total_gdp:,.0f}")
        spread = self.utility_spread_pct()
        lines.append(f"Utility spread: {spread:.1f}% (smaller = closer to classic R-R equilibrium)")
        lines.append(f"Converged: {self.converged} ({self.iterations} iterations)")
        return "\n".join(lines)
