"""Production functions, agglomeration economies, and wage determination"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_production.ipynb.

# %% auto 0
__all__ = ["calculate_tfp", "calculate_output", "calculate_wage", "output_per_worker", "agglomeration_factor"]

# %% ../nbs/06_production.ipynb 2
import numpy as np


# %% ../nbs/06_production.ipynb 4
def calculate_tfp(
    population: float,  # City population (= labour)
    base_tfp: float,  # Base TFP (productivity when L=1)
    eta: float,  # Agglomeration elasticity
) -> float:
    """Calculate total factor productivity with agglomeration."""
    return base_tfp * (population**eta)


def calculate_output(
    population: float,  # City population (= labour)
    base_tfp: float,  # Base TFP
    alpha: float = 0.65,  # Labour share in production
    eta: float = 0.04,  # Agglomeration elasticity
) -> float:
    """Calculate total output with agglomeration economies."""
    tfp = calculate_tfp(population, base_tfp, eta)
    return tfp * (population**alpha)


def calculate_wage(
    population: float,  # City population (= labour)
    base_tfp: float,  # Base TFP
    alpha: float = 0.65,  # Labour share in production
    eta: float = 0.04,  # Agglomeration elasticity
) -> float:
    """Calculate equilibrium wage as marginal product of labour."""
    tfp = calculate_tfp(population, base_tfp, eta)
    return alpha * tfp * (population ** (alpha - 1))


def output_per_worker(
    population: float,  # City population
    base_tfp: float,  # Base TFP
    alpha: float = 0.65,  # Labour share
    eta: float = 0.04,  # Agglomeration elasticity
) -> float:
    """Calculate output per worker (labour productivity)."""
    return calculate_output(population, base_tfp, alpha, eta) / population


def agglomeration_factor(
    population: float,  # Population of city of interest
    reference_population: float,  # Population of reference city
    eta: float,  # Agglomeration elasticity
) -> float:
    """Calculate the TFP multiplier from agglomeration relative to a reference city."""
    return (population / reference_population) ** eta
