"""Worker utility functions and the spatial indifference principle"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_utility.ipynb.

# %% auto 0
__all__ = ["calculate_utility", "utility_compensating_wage"]

# %% ../nbs/04_utility.ipynb 2
import numpy as np


# %% ../nbs/04_utility.ipynb 5
# | echo: true
def calculate_utility(wage: float, rent: float, amenity: float = 1.0, beta: float = 0.33) -> float:
    """Calculate worker utility using CES specification."""
    return (wage / (rent**beta)) * amenity


def utility_compensating_wage(rent_ratio: float, amenity_ratio: float = 1.0, beta: float = 0.33) -> float:
    """Calculate the wage ratio needed to maintain constant utility."""
    return (rent_ratio**beta) / amenity_ratio
